# Generated by Django 3.2.6 on 2021-08-07 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_info', models.TextField(default='NOT SET', verbose_name='Background Infomation')),
                ('phone_num', models.CharField(default='NOT SET', max_length=10, verbose_name='Phone Number')),
                ('twitter', models.TextField(default='NOT SET', verbose_name='Twitter')),
                ('facebook', models.TextField(default='NOT SET', verbose_name='Facebook')),
                ('line', models.TextField(default='NOT SET', verbose_name='LINE')),
                ('age', models.CharField(default='NOT SET', max_length=2, verbose_name='Age')),
                ('home_address', models.TextField(default='NOT SET', verbose_name='Home Address')),
                ('home_postalcode', models.TextField(default='NOT SET', verbose_name='Home Postal Code')),
                ('home_province', models.TextField(default='NOT SET', verbose_name='Home Province')),
                ('home_district', models.TextField(default='NOT SET', verbose_name='Home District')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.TextField(default='NOT SET', verbose_name='Barcode')),
                ('brand', models.TextField(default='NOT SET', verbose_name='Battery Brand')),
                ('battery_type', models.TextField(default='NOT SET', verbose_name='Battery Type')),
                ('battery_model', models.TextField(default='NOT SET', verbose_name='Battery Model')),
                ('warranty_period', models.TextField(default='NOT SET', verbose_name='Warranty Period')),
                ('date_installed', models.DateTimeField()),
                ('shop_name', models.TextField(default='NOT SET', verbose_name='Shop Name')),
                ('shop_province', models.TextField(default='NOT SET', verbose_name='Shop Province')),
                ('shop_district', models.TextField(default='NOT SET', verbose_name='Shop District')),
                ('shop_phonenumber', models.TextField(default='NOT SET', verbose_name='Shop Phone Number')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile')),
            ],
        ),
    ]
