# Generated by Django 2.2.5 on 2021-08-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterywarranty',
            name='barcode',
            field=models.CharField(default='NOT SET', max_length=13, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='batterywarranty',
            name='battery_model',
            field=models.CharField(default='NOT SET', max_length=20, verbose_name='Battery Model'),
        ),
        migrations.AlterField(
            model_name='batterywarranty',
            name='battery_type',
            field=models.CharField(default='NOT SET', max_length=20, verbose_name='Battery Type'),
        ),
        migrations.AlterField(
            model_name='batterywarranty',
            name='brand',
            field=models.CharField(default='NOT SET', max_length=20, verbose_name='Battery Brand'),
        ),
        migrations.AlterField(
            model_name='batterywarranty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='batterywarranty',
            name='shop_district',
            field=models.CharField(default='NOT SET', max_length=20, verbose_name='Shop District'),
        ),
        migrations.AlterField(
            model_name='batterywarranty',
            name='shop_phonenumber',
            field=models.CharField(default='NOT SET', max_length=11, verbose_name='Shop Phone Number'),
        ),
        migrations.AlterField(
            model_name='batterywarranty',
            name='shop_province',
            field=models.CharField(default='NOT SET', max_length=20, verbose_name='Shop Province'),
        ),
        migrations.AlterField(
            model_name='batterywarranty',
            name='warranty_period',
            field=models.CharField(default='NOT SET', max_length=20, verbose_name='Warranty Period'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
