# Generated by Django 3.2.6 on 2021-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210827_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterywarranty',
            name='date_installed',
            field=models.DateField(),
        ),
    ]
